export * from './clinic.interface';
export * from './clinicCreatePatchPayload.interface';
export * from './clinicCreatePostPayload.interface';
export * from './clinicQueryParams.interface';
export * from './clinicCardData.interface';
export * from './clinicPatientTableData.interface';
export * from './clinicPaymentTableData.interface';
export * from './clinicViewLineChartData.interface';
export * from './clinicLineChart.interface';
